return {
  'nvim-treesitter/nvim-treesitter',
  build = ':TSUpdate',
  config = function()
    require('nvim-treesitter.configs').setup {
      ensure_installed = {
        "bash",
        "c",
        "cmake",
        "cpp",
        "css",
        "csv",
        "dockerfile",
        "elixir",
        "git_config",
        "gitignore",
        "go",
        "graphql",
        "helm",
        "html",
        "http",
        "java",
        "javadoc",
        "javascript",
        "jq",
        "jinja",
        "json",
        "julia",
        "kotlin",
        "lua",
        "markdown",
        "markdown_inline",
        "nginx",
        "perl",
        "php",
        "pug",
        "python",
        "regex",
        "scala",
        "sql",
        "tsv",
        "tsx",
        "typescript",
        "vim",
        "vimdoc",
        "xml",
        "yaml"
      },
      highlight = { enable = true },
      indent = { enable = true },
    }
  end
}

